services:
  ani-notify:
    container_name: Ani-Notify
    restart: always
    ports:
      - 3000:3000
    image: ghcr.io/tohjuler/ani-notify:latest
    links:
      - consumet:consumet
    env_file:
      - stack.env
    volumes:
      - ./stack.env:/usr/src/app/.env
      - db:/usr/src/app/db/
  consumet:
    image: riimuru/consumet-api
    restart: always

volumes:
  db: