name: Bun-Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
      - run: cp .env.example .env
      #- run: sed -i 's@DATABASE_URL=.*@DATABASE_URL=${{ secrets.TEST_DB_STRING }}@' .env
      - name: Set up test db string
        uses: MathieuSoysal/replace-string-in-file@v1.1.0
        with:
          file: .env
          old-string: 'DATABASE_URL=.*'
          new-string: "${{ secrets.TEST_DB_STRING }}"
      - run: bun install -p
      - run: bun run db:init
      # - run: bun test # The user tests can't be runned in github actions
      - run: bun test tests/index.test.ts
