name: Bun-Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
      - run: cp .env.example .env
      - run: bun install -p
      - run: bun run db:init
      # - run: bun test # The user tests can't be runned in github actions
      - run: bun test tests/index.test.ts
